### ISSUE TITLE
public function public not allowed

### ISSUE THREAD

**Issue by yuyinitos** [htunlogic/laravel-poloniex#3]
I'm running on PHP 7.1 and the function declaration below is not allowed in Client.php line 300. Public is a restricted keyword. Renaming the function to something else (e.g. publicApi) solves the issue.

`    public function public(array $parameters)
`

**Comment by xartem** [comment]
I'm get some error on PHP 7.0.11
This issue when i call in shedule on Kernel.php
$schedule->call('App\Http\Controllers\NotifyController@shedule')->everyMinute();

[2017-07-07 17:22:01] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC), expecting identifier (T_STRING)' in /home/nick/domains/***/private_html/vendor/htunlogic/laravel-poloniex/src/Client.php:300
Stack trace:
#0 {main}

**Comment by htunlogic** [comment]
When getting this error it means you are not using PHP7. Check your IDE settings for PHP interpreter and set it to 7.0 or higher, and also, check that the version of PHP on your system is actually 7 or higher. If you made upgrade, also check that your FPM is consistent with php version.
